package de.voize.reaktnativetoolkit.ksp.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.ParameterizedTypeName
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.DOUBLE
import com.squareup.kotlinpoet.FLOAT
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.LONG
import com.squareup.kotlinpoet.ksp.toTypeName
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Generator for React Native new architecture iOS code.
 */
internal class NewArchIOSGenerator(
    private val codeGenerator: CodeGenerator,
    private val config: NewArchConfig,
    private val logger: KSPLogger,
) {
    private val outputPath = generatedCommonFilePath + config.outputPath

    fun generate(rnModules: List<ReactNativeModuleGenerator.RNModule>) {
        if (rnModules.isEmpty()) return

        generateSharedTypesFile()
        rnModules.forEach { module ->
            generateSwiftNativeModule(module)
        }

        generateObjCBridgeFile(rnModules)
    }

    private fun hasFlows(module: ReactNativeModuleGenerator.RNModule): Boolean {
        return module.reactNativeFlows.isNotEmpty()
    }

    private fun generateSharedTypesFile() {
        val swiftCode = buildString {
            appendLine("//")
            appendLine("//  RNTypes.swift")
            appendLine("//")
            appendLine("//  Generated by reakt-native-toolkit for React Native 0.83+ new architecture.")
            appendLine("//  Shared type definitions for all native modules.")
            appendLine("//  Do not modify manually.")
            appendLine("//")
            appendLine()
            appendLine("import Foundation")
            appendLine()
            appendLine("// Type aliases for React Native promise callbacks")
            appendLine("typealias RCTPromiseResolveBlock = (Any?) -> Void")
            appendLine("typealias RCTPromiseRejectBlock = (String?, String?, Error?) -> Void")
        }

        writeFile("RNTypes.swift", swiftCode)
    }

    private fun generateSwiftNativeModule(module: ReactNativeModuleGenerator.RNModule) {
        val moduleName = module.moduleName
        val className = "Native${moduleName}"
        val bridgeName = "${moduleName}Bridge"
        val bridgeKtName = "${bridgeName}Kt"

        val methods = module.reactNativeMethods.map { method ->
            generateSwiftMethod(module, method, bridgeKtName)
        }

        val flowMethods = module.reactNativeFlows.map { flow ->
            generateSwiftFlowMethod(module, flow, bridgeKtName)
        }

        val swiftCode = buildString {
            appendLine("//")
            appendLine("//  $className.swift")
            appendLine("//")
            appendLine("//  Generated by reakt-native-toolkit for React Native 0.83+ new architecture.")
            appendLine("//  Do not modify manually.")
            appendLine("//")
            appendLine()
            appendLine("import Foundation")
            appendLine("import React")
            appendLine("import ${config.kmpFrameworkName}")
            appendLine()
            appendLine("@objc($moduleName)")
            appendLine("class $className: NSObject {")
            appendLine()
            appendLine("    @objc static func moduleName() -> String {")
            appendLine("        return \"$moduleName\"")
            appendLine("    }")
            appendLine()
            appendLine("    @objc static func requiresMainQueueSetup() -> Bool {")
            appendLine("        return false")
            appendLine("    }")

            methods.forEach { method ->
                appendLine()
                append(method)
            }

            flowMethods.forEach { flowMethod ->
                appendLine()
                append(flowMethod)
            }

            if (hasFlows(module)) {
                appendLine()
                append(generateUnsubscribeMethod(module, bridgeKtName))
            }

            appendLine("}")
        }

        writeFile("$className.swift", swiftCode)
    }

    private fun generateSwiftMethod(
        module: ReactNativeModuleGenerator.RNModule,
        method: KSFunctionDeclaration,
        bridgeKtName: String
    ): String {
        val methodName = method.simpleName.asString()
        val parameters = method.parameters
        val errorCode = "${config.errorCodePrefix}_${module.moduleName.uppercase()}_ERROR"

        val objcSelector = buildObjcSelector(methodName, parameters)

        val swiftParams = buildSwiftMethodParams(methodName, parameters)

        val bridgeCall = buildBridgeCall(module.moduleName, methodName, parameters, bridgeKtName, errorCode)

        return buildString {
            appendLine("    /// ${methodName}")
            appendLine("    @objc($objcSelector)")
            if (parameters.isEmpty()) {
                appendLine("    func $methodName(_ resolve: @escaping RCTPromiseResolveBlock,")
                appendLine("                reject: @escaping RCTPromiseRejectBlock) {")
            } else {
                appendLine("    func $methodName($swiftParams,")
                appendLine("                  resolve: @escaping RCTPromiseResolveBlock,")
                appendLine("                  reject: @escaping RCTPromiseRejectBlock) {")
            }
            appendLine()
            appendLine(bridgeCall.prependIndent("        "))
            appendLine("    }")
        }
    }

    private fun generateSwiftFlowMethod(
        module: ReactNativeModuleGenerator.RNModule,
        flow: KSFunctionDeclaration,
        bridgeKtName: String
    ): String {
        val methodName = flow.simpleName.asString()
        val parameters = flow.parameters
        val errorCode = "${config.errorCodePrefix}_${module.moduleName.uppercase()}_ERROR"

        val objcSelector = buildObjcSelectorForFlow(methodName, parameters)
        val swiftParams = buildSwiftFlowMethodParams(methodName, parameters)
        val bridgeCall = buildBridgeCallForFlow(module.moduleName, methodName, parameters, bridgeKtName, errorCode)

        return buildString {
            appendLine("    /// ${methodName} (Flow)")
            appendLine("    @objc($objcSelector)")
            appendLine("    func $methodName($swiftParams,")
            appendLine("                  resolve: @escaping RCTPromiseResolveBlock,")
            appendLine("                  reject: @escaping RCTPromiseRejectBlock) {")
            appendLine()
            appendLine(bridgeCall.prependIndent("        "))
            appendLine("    }")
        }
    }

    private fun generateUnsubscribeMethod(
        module: ReactNativeModuleGenerator.RNModule,
        bridgeKtName: String
    ): String {
        val errorCode = "${config.errorCodePrefix}_${module.moduleName.uppercase()}_ERROR"

        return buildString {
            appendLine("    /// Unsubscribe from a flow")
            appendLine("    @objc(unsubscribeFromToolkitUseFlow:resolve:reject:)")
            appendLine("    func unsubscribeFromToolkitUseFlow(_ subscriptionId: String,")
            appendLine("                  resolve: @escaping RCTPromiseResolveBlock,")
            appendLine("                  reject: @escaping RCTPromiseRejectBlock) {")
            appendLine()
            appendLine("        // Call Kotlin bridge function")
            appendLine("        $bridgeKtName.unsubscribeFromToolkitUseFlowFromJS(")
            appendLine("            subscriptionId: subscriptionId,")
            appendLine("            onSuccess: { result in")
            appendLine("                resolve(result)")
            appendLine("            },")
            appendLine("            onError: { error in")
            appendLine("                reject(\"$errorCode\", error, nil)")
            appendLine("            }")
            appendLine("        )")
            appendLine("    }")
        }
    }

    private fun buildObjcSelector(methodName: String, parameters: List<KSValueParameter>): String {
        return buildString {
            append(methodName)
            if (parameters.isEmpty()) {
                append(":reject:")
            } else {
                parameters.forEachIndexed { index, param ->
                    if (index == 0) {
                        append(":")
                    } else {
                        append("${param.name?.asString()}:")
                    }
                }
                append("resolve:reject:")
            }
        }
    }

    private fun buildObjcSelectorForFlow(methodName: String, parameters: List<KSValueParameter>): String {
        return buildString {
            append(methodName)
            append(":previous:")
            parameters.forEach { param ->
                append("${param.name?.asString()}:")
            }
            append("resolve:reject:")
        }
    }

    private fun buildSwiftMethodParams(methodName: String, parameters: List<KSValueParameter>): String {
        if (parameters.isEmpty()) {
            return ""
        }

        return parameters.mapIndexed { index, param ->
            val paramName = param.name?.asString() ?: "param$index"
            val swiftType = getSwiftType(param)
            if (index == 0) {
                "_ $paramName: $swiftType"
            } else {
                "$paramName: $swiftType"
            }
        }.joinToString(",\n                  ")
    }

    private fun buildSwiftFlowMethodParams(methodName: String, parameters: List<KSValueParameter>): String {
        val flowParams = mutableListOf<String>()
        flowParams.add("_ subscriptionId: String")
        flowParams.add("previous: String?")

        parameters.forEachIndexed { index, param ->
            val paramName = param.name?.asString() ?: "param$index"
            val swiftType = getSwiftType(param)
            flowParams.add("$paramName: $swiftType")
        }

        return flowParams.joinToString(",\n                  ")
    }

    private fun getSwiftType(param: KSValueParameter): String {
        val type = param.type.toTypeName()
        return when (type) {
            STRING -> "String"
            BOOLEAN -> "Bool"
            INT -> "Double" // JS numbers are Double
            LONG -> "Double"
            FLOAT -> "Double"
            DOUBLE -> "Double"
            is ClassName -> when (type.canonicalName) {
                "kotlin.String" -> "String"
                "kotlin.Boolean" -> "Bool"
                "kotlin.Int" -> "Double"
                "kotlin.Long" -> "Double"
                "kotlin.Float" -> "Double"
                "kotlin.Double" -> "Double"
                else -> "String" // Custom types are JSON serialized
            }
            is ParameterizedTypeName -> "String" // Collections are JSON serialized
            else -> "String" // Default to String for unknown types
        }
    }

    private fun buildBridgeCall(
        moduleName: String,
        methodName: String,
        parameters: List<KSValueParameter>,
        bridgeKtName: String,
        errorCode: String
    ): String {
        val bridgeFunctionName = "${methodName}FromJS"

        return buildString {
            appendLine("// Call Kotlin bridge function")
            appendLine("$bridgeKtName.$bridgeFunctionName(")

            parameters.forEachIndexed { index, param ->
                val paramName = param.name?.asString() ?: "param$index"
                val swiftType = getSwiftType(param)

                val bridgeParamName = if (swiftType == "String" && !isPrimitiveString(param)) {
                    "json${paramName.replaceFirstChar { it.uppercase() }}"
                } else {
                    paramName
                }

                appendLine("    $bridgeParamName: $paramName,")
            }

            appendLine("    onSuccess: { result in")
            appendLine("        resolve(result)")
            appendLine("    },")
            appendLine("    onError: { error in")
            appendLine("        reject(\"$errorCode\", error, nil)")
            appendLine("    }")
            append(")")
        }
    }

    private fun buildBridgeCallForFlow(
        moduleName: String,
        methodName: String,
        parameters: List<KSValueParameter>,
        bridgeKtName: String,
        errorCode: String
    ): String {
        val bridgeFunctionName = "${methodName}FromJS"

        return buildString {
            appendLine("// Call Kotlin bridge function for Flow")
            appendLine("$bridgeKtName.$bridgeFunctionName(")
            appendLine("    subscriptionId: subscriptionId,")
            appendLine("    previous: previous,")

            parameters.forEachIndexed { index, param ->
                val paramName = param.name?.asString() ?: "param$index"
                val swiftType = getSwiftType(param)

                val bridgeParamName = if (swiftType == "String" && !isPrimitiveString(param)) {
                    "json${paramName.replaceFirstChar { it.uppercase() }}"
                } else {
                    paramName
                }

                appendLine("    $bridgeParamName: $paramName,")
            }

            appendLine("    onSuccess: { result in")
            appendLine("        resolve(result)")
            appendLine("    },")
            appendLine("    onError: { error in")
            appendLine("        reject(\"$errorCode\", error, nil)")
            appendLine("    }")
            append(")")
        }
    }

    private fun isPrimitiveString(param: KSValueParameter): Boolean {
        val type = param.type.toTypeName()
        return type == STRING || (type is ClassName && type.canonicalName == "kotlin.String")
    }

    private fun generateObjCBridgeFile(rnModules: List<ReactNativeModuleGenerator.RNModule>) {
        val objcCode = buildString {
            appendLine("//")
            appendLine("//  RNModuleBridge.m")
            appendLine("//")
            appendLine("//  Generated by reakt-native-toolkit for React Native 0.83+ new architecture.")
            appendLine("//  Objective-C bridge file to export Swift modules to React Native.")
            appendLine("//  This uses RCT_EXTERN_MODULE and RCT_EXTERN_METHOD macros to register")
            appendLine("//  methods with React Native's TurboModule interop layer.")
            appendLine("//  Do not modify manually.")
            appendLine("//")
            appendLine()
            appendLine("#import <React/RCTBridgeModule.h>")
            appendLine()

            rnModules.forEach { module ->
                append(generateObjCModuleDeclaration(module))
                appendLine()
            }
        }

        writeFile("RNModuleBridge.m", objcCode)
    }

    private fun generateObjCModuleDeclaration(module: ReactNativeModuleGenerator.RNModule): String {
        val moduleName = module.moduleName

        return buildString {
            appendLine("// $moduleName - ${module.wrappedClassDeclaration.simpleName.asString()}")
            appendLine("@interface RCT_EXTERN_MODULE($moduleName, NSObject)")
            appendLine()

            module.reactNativeMethods.forEach { method ->
                append(generateObjCMethodDeclaration(method))
                appendLine()
            }

            module.reactNativeFlows.forEach { flow ->
                append(generateObjCFlowMethodDeclaration(flow))
                appendLine()
            }

            if (hasFlows(module)) {
                append(generateObjCUnsubscribeMethodDeclaration())
                appendLine()
            }

            appendLine("@end")
        }
    }

    private fun generateObjCMethodDeclaration(method: KSFunctionDeclaration): String {
        val methodName = method.simpleName.asString()
        val parameters = method.parameters

        return buildString {
            append("RCT_EXTERN_METHOD($methodName:")

            if (parameters.isEmpty()) {
                appendLine("(RCTPromiseResolveBlock)resolve")
                appendLine("                  reject:(RCTPromiseRejectBlock)reject)")
            } else {
                parameters.forEachIndexed { index, param ->
                    val paramName = param.name?.asString() ?: "param$index"
                    val objcType = getObjCType(param)

                    if (index == 0) {
                        appendLine("($objcType *)$paramName")
                    } else {
                        appendLine("                  $paramName:($objcType *)$paramName")
                    }
                }
                appendLine("                  resolve:(RCTPromiseResolveBlock)resolve")
                appendLine("                  reject:(RCTPromiseRejectBlock)reject)")
            }
        }
    }

    private fun generateObjCFlowMethodDeclaration(flow: KSFunctionDeclaration): String {
        val methodName = flow.simpleName.asString()
        val parameters = flow.parameters

        return buildString {
            append("RCT_EXTERN_METHOD($methodName:")
            appendLine("(NSString *)subscriptionId")
            appendLine("                  previous:(NSString *)previous")

            parameters.forEachIndexed { index, param ->
                val paramName = param.name?.asString() ?: "param$index"
                val objcType = getObjCType(param)
                appendLine("                  $paramName:($objcType *)$paramName")
            }

            appendLine("                  resolve:(RCTPromiseResolveBlock)resolve")
            appendLine("                  reject:(RCTPromiseRejectBlock)reject)")
        }
    }

    private fun generateObjCUnsubscribeMethodDeclaration(): String {
        return buildString {
            appendLine("RCT_EXTERN_METHOD(unsubscribeFromToolkitUseFlow:(NSString *)subscriptionId")
            appendLine("                  resolve:(RCTPromiseResolveBlock)resolve")
            appendLine("                  reject:(RCTPromiseRejectBlock)reject)")
        }
    }

    private fun getObjCType(param: KSValueParameter): String {
        val type = param.type.toTypeName()
        return when (type) {
            STRING -> "NSString"
            BOOLEAN -> "NSNumber" // Booleans are NSNumber in ObjC
            INT, LONG, FLOAT, DOUBLE -> "NSNumber"
            is ClassName -> when (type.canonicalName) {
                "kotlin.String" -> "NSString"
                "kotlin.Boolean" -> "NSNumber"
                "kotlin.Int", "kotlin.Long", "kotlin.Float", "kotlin.Double" -> "NSNumber"
                else -> "NSString" // Custom types are JSON serialized as String
            }
            is ParameterizedTypeName -> "NSString" // Collections are JSON serialized
            else -> "NSString"
        }
    }

    private fun writeFile(fileName: String, content: String) {
        val filePath = outputPath + fileName.substringBeforeLast(".")
        val extension = fileName.substringAfterLast(".")

        val file = codeGenerator.createNewFileByPath(
            dependencies = Dependencies.ALL_FILES,
            path = filePath,
            extensionName = extension,
        )
        OutputStreamWriter(file, StandardCharsets.UTF_8).use { it.write(content) }
        file.close()
    }
}
